test/Web/DemoControllerTest.php
test/Web/IndexControllerTest.php
test/Web/RedisControllerTest.php

add DemoControllerTest, and separate RequestTest

add DemoControllerTest, and separate RequestTest

---

app/Controllers/RouteController.php

access /routes you can see all registered routes.

up: add example route /routes

---

.travis.yml

travis tests have passed, or you can use `expect` to control it.

Fix the pecl installation.

---

Dockerfile

Install bcmath

---

composer.json

composer.json add ext-swoole

---

composer.json
dev.composer.json

add php-cs-fixer and format `composer.json`

add php-cs-fixer

---

app/Controllers/Psr7Controller.php

- Verify https://github.com/swoft-cloud/swoft/issues/247

add multiFilesInOneKey action to Psr7Controller

---

Dockerfile

keep swoft master process PID = 1, for receive docker stop signal(`SIGTERM`)

Dockerfile: replace CMD to ENTRYPOINT

---

.env.example
config/server.php

修改pfile默认位置

---

app/Controllers/ExceptionController.php

fix: Fix typo.

---

config/properties/app.php

fix https://github.com/swoft-cloud/swoft/issues/522

fix:lang config is error

---

app/Annotation/Mapping/AlphaDash.php
app/Annotation/Parser/AlphaDashParser.php
app/Http/Controller/ValidatorController.php
app/Validator/CustomerValidator.php
app/Validator/Rule/AlphaDashRule.php
app/Validator/TestValidator.php

add Validator Demo

---

app/Annotation/Mapping/AlphaDash.php
app/Http/Controller/ValidatorController.php
app/Validator/TestValidator.php

Remove the inheritance Type class of AlphaDash

---

composer.cn.json

According to https://learnku.com/articles/30758, so we would better
to update.

Update composer mirror

---

.gitignore
Dockerfile

主要是两点：
1. 优化Dockerfile指令逻辑
让基础环境的安装与composer安装指令分层，这样基础环境的安装能够使用上构建缓存，构建更快速。
2. 添加了tmp/目录的忽略
这个是docker-compose.yml中指定存放mysql数据的目录。

优化Dockerfile，增加gitignore目录

---

.travis.yml
app/Console/Command/AgentCommand.php
app/Http/Controller/BeanController.php
app/Http/Controller/DbModelController.php
app/Http/Controller/RespController.php
app/Listener/DeregisterServiceListener.php
app/Listener/ModelSavedListener.php
app/Listener/RanListener.php
app/Listener/RegisterServiceListener.php
app/Listener/UserSavingListener.php
app/WebSocket/Chat/HomeController.php
composer.json
phpstan.neon.dist
test/bootstrap.php

Introduce PHPStan

---

phpstan.neon.dist

@inhere https://github.com/swoft-cloud/swoft/pull/864#issuecomment-516722647

Ignore current 17 static analysis errors

---

app/WebSocket/Test/TestController.php
phpstan.neon.dist

Follow changes in swoole-ide-helper

---

app/Http/Controller/HomeController.php
resource/views/home/ws-test.php

up: add ws test page

---

README.md

English documentation link does't work.

English documentation url

---

app/Console/Command/TestCommand.php
app/Http/Controller/RedisController.php

change ab test curreccy

---

app/Aspect/BeanAspect.php
app/Aspect/RequestBeanAspect.php
app/Common/MyBean.php
app/Common/RpcProvider.php
app/Http/Controller/BeanController.php
app/Http/Controller/HomeController.php
app/Http/Controller/SelectDbController.php
app/Model/Data/GoodsData.php
app/Model/Logic/ConsulLogic.php
app/Model/Logic/RequestBean.php
app/WebSocket/Chat/HomeController.php
app/WebSocket/ChatModule.php
app/WebSocket/Middleware/GlobalWsMiddleware.php
app/bean.php
config/app.php
database/Migration/Count.php
database/Migration/Desc.php

add more examples

---

Dockerfile

**Change Dockerfile.**
1. Add clear apt cache.
2. Change $APP_ENV = test.If use the current default configuration, if you do not pay attention, it will boot to the online machine.
3. Add `ping` `ifconfig` command.
Because this negligence caused an online failure.

update: Dockerfile

---

README.md

Typo fix on "corntab"
Its a great project, so i felt to fix the typo.

Typo Fix: CORNTAB to CRONTAB

---

README.zh-CN.md

correct the docs links.
- [ x] Added/updated tests
- [x ] Added/updated documentation

correct the docs links

---

.php_cs
app/Http/Middleware/DomainLimitMiddleware.php
test/README.md
test/unit/Common/MyBeanTest.php

update some examples

---

composer.cn.json
composer.dev.json
composer.json
dev.composer.json

update for phpunit version
